from __future__ import annotations

from typing import Any, Protocol
from codepilot.domain.models import Screenshot


class AIService(Protocol):
    def get_model(self, preference: str) -> Any: ...
    def inspect_problem(self, screenshots: list[tuple[bytes, str]], model: Any | None = None) -> dict[str, Any]: ...
    def solve(self, problem: dict[str, Any], previous_code: str | None = None, failure: dict[str, Any] | None = None, model: Any | None = None) -> str: ...
    def inspect_result(self, image: bytes, mime: str, model: Any | None = None) -> dict[str, Any]: ...
    def model_name(self, model: Any) -> str: ...
    def close(self) -> None: ...


class InputService(Protocol):
    def capture(self, force: bool = False) -> tuple[bytes, str]: ...
    def type_code(self, text: str, existing_text: str | None = None) -> None: ...
    def pause(self) -> None: ...
    def resume(self) -> None: ...
    def stop(self) -> None: ...
    @property
    def is_paused(self) -> bool: ...


class HotkeyService(Protocol):
    def run(self, handlers: dict[str, Any]) -> None: ...
    def stop(self) -> None: ...
